Cost Tracking Change Log
vellum-ai/vellum-client-generator pull request #347
Opened 2024-08-08 22:50 UTC by marlenc3

2024-08-08 23:45 UTC, dvargas92495 requested changes

2024-08-08 23:45 UTC, dvargas92495 commented on fern/docs/content/change-log/2024-08.mdx
> +## Prompt Cost Tracking
[blocking] let's add this towards the top, we go from most recent -> least recent

2024-08-08 23:45 UTC, dvargas92495 commented on fern/docs/content/change-log/2024-08.mdx
> +![MLModel Detail Page with Billing Config](mlmodel_detail_page_with_cost_config.png)
[blocking] CI is breaking on this link

2024-08-08 23:45 UTC, dvargas92495 commented on fern/docs/content/change-log/2024-08.mdx
> +If you're curious about the pricing information, feel free to additionally look into a Model's page.
```suggestion
If you're curious about the pricing information, feel free to look into a Model's details page.
```

2024-08-08 23:45 UTC, dvargas92495 commented on fern/docs/content/change-log/2024-08.mdx
> +You can now see cost tracking in prompt sandboxes, both in the prompt editor and in the comparison tab!
[nit] Let's add some copy here that says that we are tracking the cost from the provider. Let's also add something towards the end hinting that it's available for OpenAI, Anthropic, and Google models, with the rest to follow in the coming days

2024-08-09 15:37 UTC, noanflaherty approved these changes
Nice work! Let's please iterate based on my suggestions before merging, but we can turn on the feature flag for everyone whenever.

In case it's helpful, we have some guidelines for writing stuff for the changelog here: https://www.notion.so/vellum-ai/Guide-to-Writing-Product-Updates-6ebad76d47274d7180a55eef13946bbd

2024-08-09 15:37 UTC, noanflaherty commented on fern/docs/content/change-log/2024-08.mdx
> +## Prompt Cost Tracking
```suggestion
## Prompt Sandbox Cost Tracking
```

2024-08-09 15:37 UTC, noanflaherty commented on fern/docs/content/change-log/2024-08.mdx
> +You can now see cost tracking for input and output tokens in prompt sandboxes, both in the prompt editor and in the comparison tab!
```suggestion
You can now see the dollar cost of a Prompt's execution within both a Prompt Sandbox's Prompt Editor and Comparison Mode views.
```

2024-08-09 15:37 UTC, noanflaherty commented on fern/docs/content/change-log/2024-08.mdx
> +Cost of input and output tokens are being tracked from providers.
These costs are calculated using model providers' publicly available pricing data in conjunction with the number of input/output tokens used.

2024-08-09 15:37 UTC, noanflaherty commented on fern/docs/content/change-log/2024-08.mdx
> +Most popular models are already supported, with even more models following in the coming days.
```suggestion
If you're curious about a given model's pricing, you can view details in the Model's detail page.
![MLModel Detail Page with Billing Config](https://storage.cloud.google.com/vellum-public/help-docs/changelogs/2024-08/mlmodel_detail_page_with_cost_config.png)

Most popular models already have pricing information populated, with support for even more models following in the coming days.

Showing cost information in Prompt Sandboxes is just the first step! We'll expose cost details throughout more of Vellum over time.
```

2024-08-09 15:37 UTC, noanflaherty commented on fern/docs/content/change-log/2024-08.mdx
> +![Prompt Sandbox Comparison With Cost Tracking](https://storage.cloud.google.com/vellum-public/help-docs/changelogs/2024-08/prompt_sandbox_comparison_with_cost_tracking.png)
Looking at these images, I feel like we should round to 9 significant digits. the long-tail of 99999999 feels overkill.

2024-08-09 15:37 UTC, noanflaherty commented on fern/docs/content/change-log/2024-08.mdx
> +![Prompt Sandbox Comparison With Cost Tracking](https://storage.cloud.google.com/vellum-public/help-docs/changelogs/2024-08/prompt_sandbox_comparison_with_cost_tracking.png)
Also, while true, the definition of Vellum here is pretty gruesome and makes me think we could use a screenshot of another example 😅

2024-08-09 18:26 UTC, dvargas92495 approved these changes

2024-08-09 18:26 UTC, dvargas92495 commented on fern/docs/content/change-log/2024-08.mdx
> +_August 9th, 22024_
```suggestion
_August 9th, 2024_
```

2024-08-09 19:39 UTC, merged